version: 2
jobs:
  build:
    working_directory: /ably-dotnet
    docker:
      - image: microsoft/dotnet:2-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: ls -la
      - run: cd src/IO.Ably.Tests.DotNetCore20 && dotnet test
